/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;

public class VBuscaRecepcion extends javax.swing.JFrame {
 static String Id= "";
 static String fecha= "";
  static String equipo= "";
 static String cliente= "";
 static String ci= "";
    /**
     * Creates new form VBarrio
     */
    public VBuscaRecepcion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaConsulta = new javax.swing.JTable();
        CampoBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Seleccionar = new javax.swing.JButton();
        Codigo = new javax.swing.JTextField();
        Fecha = new javax.swing.JTextField();
        Ci = new javax.swing.JTextField();
        Seleccionar1 = new javax.swing.JButton();
        ClienteNombre = new javax.swing.JTextField();
        DescriEquipo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(1250, 500));
        getContentPane().setLayout(null);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTabbedPane1.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(147, 540));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(480, 360));

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(null);

        TablaConsulta.setFont(new java.awt.Font("Purisa", 3, 12)); // NOI18N
        TablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaConsulta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 1190, 200);
        jPanel1.add(CampoBuscar);
        CampoBuscar.setBounds(1010, 10, 190, 40);

        jLabel2.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(900, 10, 110, 40);

        Seleccionar.setFont(new java.awt.Font("Purisa", 3, 18)); // NOI18N
        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(Seleccionar);
        Seleccionar.setBounds(1040, 260, 160, 40);

        Codigo.setEditable(false);
        Codigo.setFont(new java.awt.Font("Purisa", 0, 11)); // NOI18N
        jPanel1.add(Codigo);
        Codigo.setBounds(10, 20, 40, 30);

        Fecha.setEditable(false);
        Fecha.setFont(new java.awt.Font("Purisa", 0, 11)); // NOI18N
        jPanel1.add(Fecha);
        Fecha.setBounds(50, 20, 90, 30);

        Ci.setEditable(false);
        Ci.setFont(new java.awt.Font("Purisa", 0, 11)); // NOI18N
        jPanel1.add(Ci);
        Ci.setBounds(400, 20, 130, 30);

        Seleccionar1.setFont(new java.awt.Font("Purisa", 3, 18)); // NOI18N
        Seleccionar1.setText("Anular");
        Seleccionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seleccionar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Seleccionar1);
        Seleccionar1.setBounds(930, 260, 100, 40);

        ClienteNombre.setEditable(false);
        ClienteNombre.setFont(new java.awt.Font("Purisa", 0, 11)); // NOI18N
        jPanel1.add(ClienteNombre);
        ClienteNombre.setBounds(270, 20, 130, 30);

        DescriEquipo.setEditable(false);
        DescriEquipo.setFont(new java.awt.Font("Purisa", 0, 11)); // NOI18N
        jPanel1.add(DescriEquipo);
        DescriEquipo.setBounds(140, 20, 130, 30);

        jTabbedPane1.addTab("Listado", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 1220, 360);

        jLabel1.setFont(new java.awt.Font("Purisa", 3, 18)); // NOI18N
        jLabel1.setText("Recepciones");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 20, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        Id= this.Codigo.getText();
        fecha= this.Fecha.getText();
        equipo= this.DescriEquipo.getText();
        cliente= this.ClienteNombre.getText();
        ci= this.Ci.getText();
        dispose();
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void TablaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaConsultaMouseClicked
   
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaConsultaMouseClicked

    private void Seleccionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seleccionar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Seleccionar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new CBuscaRecepcion(new VBuscaRecepcion()).iniciar();            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField CampoBuscar;
    public javax.swing.JTextField Ci;
    public javax.swing.JTextField ClienteNombre;
    public javax.swing.JTextField Codigo;
    public javax.swing.JTextField DescriEquipo;
    public javax.swing.JTextField Fecha;
    private javax.swing.JButton Seleccionar;
    public javax.swing.JButton Seleccionar1;
    public javax.swing.JTable TablaConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
