/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;

public class VBuscaRecepcion1 extends javax.swing.JFrame {
 static String Id= "";
 static String cliente= "";
 static String ci= "";
 static String idacce= "";
  static String descri= "";
 static String cant= "";
    /**
     * Creates new form VBarrio
     */
    public VBuscaRecepcion1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaConsulta = new javax.swing.JTable();
        CampoBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Seleccionar = new javax.swing.JButton();
        Codigo = new javax.swing.JTextField();
        nombrecli = new javax.swing.JTextField();
        descriacc = new javax.swing.JTextField();
        codacces = new javax.swing.JTextField();
        clici = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(810, 367));
        getContentPane().setLayout(null);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTabbedPane1.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(147, 540));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(480, 360));

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));
        jPanel1.setLayout(null);

        TablaConsulta.setFont(new java.awt.Font("Purisa", 3, 12)); // NOI18N
        TablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaConsulta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 710, 130);
        jPanel1.add(CampoBuscar);
        CampoBuscar.setBounds(570, 20, 130, 30);

        jLabel2.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(590, -10, 110, 40);

        Seleccionar.setFont(new java.awt.Font("Purisa", 3, 18)); // NOI18N
        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(Seleccionar);
        Seleccionar.setBounds(560, 180, 160, 40);

        Codigo.setEditable(false);
        Codigo.setFont(new java.awt.Font("Purisa", 0, 11)); // NOI18N
        jPanel1.add(Codigo);
        Codigo.setBounds(10, 20, 40, 30);

        nombrecli.setEditable(false);
        nombrecli.setFont(new java.awt.Font("Purisa", 0, 11)); // NOI18N
        jPanel1.add(nombrecli);
        nombrecli.setBounds(50, 20, 90, 30);

        descriacc.setEditable(false);
        descriacc.setFont(new java.awt.Font("Purisa", 0, 11)); // NOI18N
        jPanel1.add(descriacc);
        descriacc.setBounds(340, 20, 130, 30);

        codacces.setEditable(false);
        codacces.setFont(new java.awt.Font("Purisa", 0, 11)); // NOI18N
        jPanel1.add(codacces);
        codacces.setBounds(270, 20, 70, 30);

        clici.setEditable(false);
        clici.setFont(new java.awt.Font("Purisa", 0, 11)); // NOI18N
        jPanel1.add(clici);
        clici.setBounds(140, 20, 130, 30);

        cantidad.setEditable(false);
        cantidad.setFont(new java.awt.Font("Purisa", 0, 11)); // NOI18N
        jPanel1.add(cantidad);
        cantidad.setBounds(470, 20, 70, 30);

        jTabbedPane1.addTab("Listado", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 40, 740, 280);

        jLabel1.setFont(new java.awt.Font("Purisa", 3, 18)); // NOI18N
        jLabel1.setText("Recepciones");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(260, 20, 150, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        Id= this.Codigo.getText();
        cliente= this.nombrecli.getText();
        ci= this.clici.getText();
        idacce= this.codacces.getText();
        descri= this.descriacc.getText();
        cant= this.cantidad.getText();
        dispose();
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void TablaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaConsultaMouseClicked
   
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaConsultaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new CBuscaRecepcion1(new VBuscaRecepcion1()).iniciar();            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField CampoBuscar;
    public javax.swing.JTextField Codigo;
    public javax.swing.JButton Seleccionar;
    public javax.swing.JTable TablaConsulta;
    public javax.swing.JTextField cantidad;
    public javax.swing.JTextField clici;
    public javax.swing.JTextField codacces;
    public javax.swing.JTextField descriacc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField nombrecli;
    // End of variables declaration//GEN-END:variables
}
