/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;

public class VBuscaSolicitud1 extends javax.swing.JFrame {

    static String Id = "";
    static String Cliente = "";
    static String Cliente1 = "";
    static String Cliente2 = "";
    static String Cliente3 = "";
    static String Cliente4 = "";
    static String Cliente5 = "";
    static String Cliente6 = "";

    /**
     * Creates new form VBarrio
     */
    public VBuscaSolicitud1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaConsulta = new javax.swing.JTable();
        CampoBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CampoCodigo = new javax.swing.JTextField();
        Campoidserv = new javax.swing.JTextField();
        servicio = new javax.swing.JTextField();
        Seleccionar1 = new javax.swing.JButton();
        cantidad = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        cliente = new javax.swing.JTextField();
        ci = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 550));
        getContentPane().setLayout(null);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTabbedPane1.setFont(new java.awt.Font("Papyrus", 3, 14)); // NOI18N
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(147, 540));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(480, 360));

        jPanel1.setBackground(new java.awt.Color(108, 99, 255));
        jPanel1.setLayout(null);

        TablaConsulta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaConsulta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 1190, 320);
        jPanel1.add(CampoBuscar);
        CampoBuscar.setBounds(1010, 10, 190, 40);

        jLabel2.setFont(new java.awt.Font("Papyrus", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(950, 10, 60, 40);

        CampoCodigo.setEditable(false);
        jPanel1.add(CampoCodigo);
        CampoCodigo.setBounds(10, 20, 40, 30);

        Campoidserv.setEditable(false);
        jPanel1.add(Campoidserv);
        Campoidserv.setBounds(50, 20, 90, 30);

        servicio.setEditable(false);
        jPanel1.add(servicio);
        servicio.setBounds(140, 20, 170, 30);

        Seleccionar1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Seleccionar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/seleccione.png"))); // NOI18N
        Seleccionar1.setText("Seleccionar");
        Seleccionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Seleccionar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Seleccionar1);
        Seleccionar1.setBounds(1020, 370, 180, 50);

        cantidad.setEditable(false);
        jPanel1.add(cantidad);
        cantidad.setBounds(310, 20, 140, 30);

        precio.setEditable(false);
        jPanel1.add(precio);
        precio.setBounds(450, 20, 120, 30);

        cliente.setEditable(false);
        jPanel1.add(cliente);
        cliente.setBounds(570, 20, 110, 30);

        ci.setEditable(false);
        jPanel1.add(ci);
        ci.setBounds(680, 20, 110, 30);

        jTabbedPane1.addTab("Listado", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 1220, 460);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Listados de Solicitud de Servicio");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 20, 350, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TablaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaConsultaMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_TablaConsultaMouseClicked

    private void Seleccionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Seleccionar1ActionPerformed
        // TODO add your handling code here:
        Id = this.CampoCodigo.getText();
        Cliente = this.Campoidserv.getText();
        Cliente1 = this.servicio.getText();
        Cliente2 = this.cantidad.getText();
        Cliente3 = this.precio.getText();
//        Cliente4 = this.equipo.getText();
        Cliente5 = this.cliente.getText();
        Cliente6 = this.ci.getText();
        dispose();
    }//GEN-LAST:event_Seleccionar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CBuscaSolicitud1(new VBuscaSolicitud1()).iniciar();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField CampoBuscar;
    public javax.swing.JTextField CampoCodigo;
    public javax.swing.JTextField Campoidserv;
    public javax.swing.JButton Seleccionar1;
    public javax.swing.JTable TablaConsulta;
    public javax.swing.JTextField cantidad;
    public javax.swing.JTextField ci;
    public javax.swing.JTextField cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTextField precio;
    public javax.swing.JTextField servicio;
    // End of variables declaration//GEN-END:variables
}
