/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.*;
import modelo.*;




/**
 *
 * @author Teresa
 */
public class VInformesFacturaC extends javax.swing.JFrame {

    /**
     * Creates new form VProducto
     */
    public VInformesFacturaC() {
        initComponents();
    }
    MBarrio modelo = new MBarrio();
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FC = new javax.swing.JButton();
        OC = new javax.swing.JButton();
        PC = new javax.swing.JButton();
        ND = new javax.swing.JButton();
        NC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 290));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Informes de Compras");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 30, 210, 30);

        FC.setText("Facturas Compras");
        FC.setToolTipText("Eliminar un registro existente");
        getContentPane().add(FC);
        FC.setBounds(330, 80, 160, 50);

        OC.setText("Orden de Compra");
        OC.setToolTipText("Cancelar Operacion");
        OC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OCActionPerformed(evt);
            }
        });
        getContentPane().add(OC);
        OC.setBounds(170, 80, 160, 50);

        PC.setText("Pedidos Compras");
        PC.setToolTipText("Guardar Registros");
        PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCActionPerformed(evt);
            }
        });
        getContentPane().add(PC);
        PC.setBounds(10, 80, 160, 50);

        ND.setText("Nota Debito Compra");
        ND.setToolTipText("Imprimir Listado");
        ND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NDActionPerformed(evt);
            }
        });
        getContentPane().add(ND);
        ND.setBounds(260, 160, 200, 50);

        NC.setText("Nota Credito Compra");
        NC.setToolTipText("Imprimir Listado");
        NC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NCActionPerformed(evt);
            }
        });
        getContentPane().add(NC);
        NC.setBounds(50, 160, 200, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
        
    }//GEN-LAST:event_formWindowActivated

    private void OCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OCActionPerformed

    private void PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PCActionPerformed

    private void NDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NDActionPerformed

    private void NCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NCActionPerformed
 public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CInformesFacturaC(new VInformesFacturaC()).iniciar();
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton FC;
    public javax.swing.JButton NC;
    public javax.swing.JButton ND;
    public javax.swing.JButton OC;
    public javax.swing.JButton PC;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
