/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.*;
import modelo.*;




/**
 *
 * @author Teresa
 */
public class VInformesRef extends javax.swing.JFrame {

    /**
     * Creates new form VProducto
     */
    public VInformesRef() {
        initComponents();
    }
    MBarrio modelo = new MBarrio();
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Clie = new javax.swing.JButton();
        ins = new javax.swing.JButton();
        Prov = new javax.swing.JButton();
        Fun = new javax.swing.JButton();
        Suc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setMinimumSize(new java.awt.Dimension(556, 271));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Informes de Referenciales");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(190, 10, 210, 30);

        Clie.setText("Clientes");
        Clie.setToolTipText("Cancelar Operacion");
        Clie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClieActionPerformed(evt);
            }
        });
        getContentPane().add(Clie);
        Clie.setBounds(180, 80, 160, 50);

        ins.setText("Insumos");
        ins.setToolTipText("Imprimir Listado");
        ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insActionPerformed(evt);
            }
        });
        getContentPane().add(ins);
        ins.setBounds(40, 170, 160, 50);

        Prov.setText("Proveedores");
        Prov.setToolTipText("Guardar Registros");
        getContentPane().add(Prov);
        Prov.setBounds(10, 80, 160, 50);

        Fun.setText("Funcionarios");
        Fun.setToolTipText("Modificar un registro existente");
        Fun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FunActionPerformed(evt);
            }
        });
        getContentPane().add(Fun);
        Fun.setBounds(350, 80, 160, 50);

        Suc.setText("Sucursales");
        Suc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SucActionPerformed(evt);
            }
        });
        getContentPane().add(Suc);
        Suc.setBounds(290, 170, 160, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SucActionPerformed
      
    }//GEN-LAST:event_SucActionPerformed

    private void FunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FunActionPerformed

    private void insActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
        
    }//GEN-LAST:event_formWindowActivated

    private void ClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClieActionPerformed
 public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CInformesRef(new VInformesRef()).iniciar();
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Clie;
    public javax.swing.JButton Fun;
    public javax.swing.JButton Prov;
    public javax.swing.JButton Suc;
    public javax.swing.JButton ins;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
