/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.*;
import modelo.*;




/**
 *
 * @author Teresa
 */
public class VInformesServicios extends javax.swing.JFrame {

    /**
     * Creates new form VProducto
     */
    public VInformesServicios() {
        initComponents();
    }
    MBarrio modelo = new MBarrio();
      /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ot = new javax.swing.JButton();
        rec = new javax.swing.JButton();
        sr = new javax.swing.JButton();
        pre = new javax.swing.JButton();
        iu = new javax.swing.JButton();
        iu1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(585, 300));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Informes de Servicios");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 10, 210, 30);

        ot.setText("Orden de Trabajo");
        ot.setToolTipText("Cancelar Operacion");
        ot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otActionPerformed(evt);
            }
        });
        getContentPane().add(ot);
        ot.setBounds(360, 80, 160, 50);

        rec.setText("Solicitud de Servicio");
        rec.setToolTipText("Guardar Registros");
        rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recActionPerformed(evt);
            }
        });
        getContentPane().add(rec);
        rec.setBounds(10, 80, 160, 50);

        sr.setText("Servicio Realizado");
        sr.setToolTipText("Cancelar Operacion");
        sr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srActionPerformed(evt);
            }
        });
        getContentPane().add(sr);
        sr.setBounds(10, 160, 160, 50);

        pre.setText("Presupuesto");
        pre.setToolTipText("Cancelar Operacion");
        pre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preActionPerformed(evt);
            }
        });
        getContentPane().add(pre);
        pre.setBounds(180, 80, 160, 50);

        iu.setText("InsumosUtilizados");
        iu.setToolTipText("Cancelar Operacion");
        iu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iuActionPerformed(evt);
            }
        });
        getContentPane().add(iu);
        iu.setBounds(170, 160, 160, 50);

        iu1.setText("Descuento");
        iu1.setToolTipText("Cancelar Operacion");
        iu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iu1ActionPerformed(evt);
            }
        });
        getContentPane().add(iu1);
        iu1.setBounds(350, 160, 160, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      
        
    }//GEN-LAST:event_formWindowActivated

    private void otActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otActionPerformed

    private void recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recActionPerformed

    private void srActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_srActionPerformed

    private void preActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_preActionPerformed

    private void iuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iuActionPerformed

    private void iu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iu1ActionPerformed
 public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CInformesServicios(new VInformesServicios()).iniciar();
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton iu;
    public javax.swing.JButton iu1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JButton ot;
    public javax.swing.JButton pre;
    public javax.swing.JButton rec;
    public javax.swing.JButton sr;
    // End of variables declaration//GEN-END:variables
}
