/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class VUsuario extends javax.swing.JFrame {
 static String Id= "";
 static String Cliente= "";
 static String Idciudad="";
 static String ciudad="";
    /**
     * Creates new form VBarrio
     */
    public VUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaConsulta = new javax.swing.JTable();
        CampoBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        CampoCodigo = new javax.swing.JTextField();
        CampoDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        codciudad = new javax.swing.JTextField();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Informe = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        codciudad4 = new javax.swing.JTextField();
        descriciudad4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CampoDescripcion1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1250, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Purisa", 3, 18)); // NOI18N
        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 20, 130, 30);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTabbedPane1.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(108, 99, 255));
        jPanel1.setLayout(null);

        TablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaConsulta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 50, 1150, 200);

        CampoBuscar.setFont(new java.awt.Font("Purisa", 3, 18)); // NOI18N
        jPanel1.add(CampoBuscar);
        CampoBuscar.setBounds(990, 20, 190, 30);

        jLabel2.setFont(new java.awt.Font("Purisa", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(890, 20, 100, 30);

        jTabbedPane1.addTab("Listado", jPanel1);

        jPanel2.setBackground(new java.awt.Color(108, 99, 255));
        jPanel2.setLayout(null);

        CampoCodigo.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(CampoCodigo);
        CampoCodigo.setBounds(240, 40, 30, 30);

        CampoDescripcion.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(CampoDescripcion);
        CampoDescripcion.setBounds(340, 40, 140, 30);

        jLabel3.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(280, 40, 70, 30);

        codciudad.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(codciudad);
        codciudad.setBounds(560, 40, 120, 30);

        Guardar.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel2.add(Guardar);
        Guardar.setBounds(440, 160, 100, 40);

        Cancelar.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel2.add(Cancelar);
        Cancelar.setBounds(570, 210, 100, 40);

        Informe.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        Informe.setText("Informe");
        jPanel2.add(Informe);
        Informe.setBounds(700, 210, 100, 40);

        Modificar.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        Modificar.setText("Modificar");
        jPanel2.add(Modificar);
        Modificar.setBounds(570, 160, 100, 40);

        Eliminar.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel2.add(Eliminar);
        Eliminar.setBounds(700, 160, 100, 40);

        nuevo.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jPanel2.add(nuevo);
        nuevo.setBounds(440, 210, 100, 40);

        jLabel4.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Codigo");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(180, 40, 60, 30);

        jLabel9.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nivel");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(480, 100, 50, 30);

        codciudad4.setEditable(false);
        codciudad4.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(codciudad4);
        codciudad4.setBounds(530, 100, 40, 30);

        descriciudad4.setEditable(false);
        descriciudad4.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(descriciudad4);
        descriciudad4.setBounds(570, 100, 100, 30);

        jButton5.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jButton5.setText("Buscar Nivel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton5FocusGained(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(670, 100, 120, 30);

        jLabel11.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Password");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(490, 40, 70, 30);

        CampoDescripcion1.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(CampoDescripcion1);
        CampoDescripcion1.setBounds(770, 40, 210, 30);

        jLabel5.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(710, 40, 70, 30);

        jTabbedPane1.addTab("Registro", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 50, 1190, 310);

        Salir.setFont(new java.awt.Font("Purisa", 1, 10)); // NOI18N
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen2/salida (2).png"))); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir);
        Salir.setBounds(1050, 370, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void TablaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaConsultaMouseClicked
this.Guardar.setEnabled(false);
  this.Modificar.setEnabled(true);
      this.Eliminar.setEnabled(true);
      this.Cancelar.setEnabled(true);
      this.CampoDescripcion.setEnabled(true);
      this.CampoDescripcion1.setEnabled(true);
      this.codciudad.setEnabled(true);
      this.nuevo.setEnabled(false);
       this.jButton5.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_TablaConsultaMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
           this.nuevo.setEnabled(false);
           this.Cancelar.setEnabled(true);
           this.Guardar.setEnabled(true);
           this.CampoDescripcion.setEnabled(true);
           this.codciudad.setEnabled(true);
           this.CampoDescripcion1.setEnabled(true);
           this.jButton5.setEnabled(true);
           this.CampoDescripcion.requestFocus();
// TODO add your handling code here:
    }//GEN-LAST:event_nuevoActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
           this.Modificar.setEnabled(false);
		   this.codciudad.setEnabled(false);
		   this.CampoDescripcion1.setEnabled(false);
          this.Eliminar.setEnabled(false);
           this.Cancelar.setEnabled(false);
           this.Guardar.setEnabled(false);
            this.nuevo.setEnabled(true);
             this.jButton5.setEnabled(false);
            this.CampoDescripcion.setEnabled(false);
		this.CampoCodigo.setText("");
		this.CampoDescripcion.setText("");
		this.codciudad.setText("");
		this.CampoDescripcion1.setText("");
		this.codciudad4.setText("");
		this.descriciudad4.setText("");

    }//GEN-LAST:event_CancelarActionPerformed

    private void jButton5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton5FocusGained
        this.codciudad4.setText(VBuscaNivel.Id);
        this.descriciudad4.setText(VBuscaNivel.Cliente);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5FocusGained

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new CBuscaNivel(new VBuscaNivel()).iniciar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
	this.Eliminar.setEnabled(false);
           this.Cancelar.setEnabled(false);
           this.Guardar.setEnabled(false);
           this.Modificar.setEnabled(false);
            this.nuevo.setEnabled(true);
             this.jButton5.setEnabled(false);
            this.CampoDescripcion.setEnabled(false);
		this.CampoCodigo.setText("");
		this.CampoDescripcion.setText("");
		this.codciudad.setText("");
		this.CampoDescripcion1.setText("");
		this.codciudad4.setText("");
		this.descriciudad4.setText("");	
		// TODO add your handling code here:
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
 new CUsuario(new VUsuario()).iniciar();   }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField CampoBuscar;
    public javax.swing.JTextField CampoCodigo;
    public javax.swing.JTextField CampoDescripcion;
    public javax.swing.JTextField CampoDescripcion1;
    public javax.swing.JButton Cancelar;
    public javax.swing.JButton Eliminar;
    public javax.swing.JButton Guardar;
    public javax.swing.JButton Informe;
    public javax.swing.JButton Modificar;
    public javax.swing.JButton Salir;
    public javax.swing.JTable TablaConsulta;
    public javax.swing.JTextField codciudad;
    public javax.swing.JTextField codciudad4;
    public javax.swing.JTextField descriciudad4;
    public javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JButton nuevo;
    // End of variables declaration//GEN-END:variables
}
