/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import controlador.*;
import vista.*;
/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class VVehiculo extends javax.swing.JFrame {
 static String Id= "";
 static String Descripcion= "";
 static String marca="";
 static String idcliente="";
  static String Nombre="";
 static String ci="";
    /**
     * Creates new form VBarrio
     */
    public VVehiculo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaConsulta = new javax.swing.JTable();
        CampoBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Seleccionar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CampoCodigo = new javax.swing.JTextField();
        CampoDescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codciudad = new javax.swing.JTextField();
        descriciudad = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Guardar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        Informe = new javax.swing.JButton();
        Modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        nuevo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codciudad1 = new javax.swing.JTextField();
        descriciudad1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        codciudad2 = new javax.swing.JTextField();
        descriciudad2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        codciudad3 = new javax.swing.JTextField();
        descriciudad3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        codciudad4 = new javax.swing.JTextField();
        descriciudad4 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        codciudad5 = new javax.swing.JTextField();
        descriciudad5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        descriciudad6 = new javax.swing.JTextField();
        Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1235, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Purisa", 0, 18)); // NOI18N
        jLabel1.setText("Vehiculos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(560, 20, 150, 30);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jTabbedPane1.setFont(new java.awt.Font("Purisa", 3, 14)); // NOI18N
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setLayout(null);

        TablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaConsulta);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 50, 1150, 360);
        jPanel1.add(CampoBuscar);
        CampoBuscar.setBounds(990, 20, 190, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(940, 20, 50, 30);

        Seleccionar.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Seleccionar.setText("Seleccionar");
        Seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(Seleccionar);
        Seleccionar.setBounds(1030, 420, 150, 40);

        jTabbedPane1.addTab("Listado", jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setLayout(null);

        CampoCodigo.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(CampoCodigo);
        CampoCodigo.setBounds(160, 70, 30, 30);

        CampoDescripcion.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(CampoDescripcion);
        CampoDescripcion.setBounds(280, 70, 120, 30);

        jLabel3.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripcion");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(200, 70, 80, 30);

        jLabel5.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Categoria");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(410, 70, 70, 30);

        codciudad.setEditable(false);
        codciudad.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(codciudad);
        codciudad.setBounds(480, 70, 40, 30);

        descriciudad.setEditable(false);
        descriciudad.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(descriciudad);
        descriciudad.setBounds(520, 70, 80, 30);

        jButton1.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jButton1.setText("Buscar Categoria");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton1FocusGained(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(600, 70, 140, 30);

        Guardar.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        Guardar.setText("Guardar");
        jPanel2.add(Guardar);
        Guardar.setBounds(450, 280, 100, 40);

        Cancelar.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        jPanel2.add(Cancelar);
        Cancelar.setBounds(580, 330, 100, 40);

        Informe.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        Informe.setText("Informe");
        jPanel2.add(Informe);
        Informe.setBounds(710, 330, 100, 40);

        Modificar.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        Modificar.setText("Modificar");
        jPanel2.add(Modificar);
        Modificar.setBounds(580, 280, 100, 40);

        Eliminar.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        Eliminar.setText("Eliminar");
        jPanel2.add(Eliminar);
        Eliminar.setBounds(710, 280, 100, 40);

        nuevo.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        nuevo.setText("Nuevo");
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jPanel2.add(nuevo);
        nuevo.setBounds(450, 330, 100, 40);

        jLabel4.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Id");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(130, 70, 30, 30);

        jLabel6.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Marca");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(760, 70, 50, 30);

        codciudad1.setEditable(false);
        codciudad1.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(codciudad1);
        codciudad1.setBounds(810, 70, 40, 30);

        descriciudad1.setEditable(false);
        descriciudad1.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(descriciudad1);
        descriciudad1.setBounds(850, 70, 100, 30);

        jButton2.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jButton2.setText("Buscar Marca");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton2FocusGained(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(950, 70, 120, 30);

        jLabel7.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tipo");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(110, 120, 50, 30);

        codciudad2.setEditable(false);
        codciudad2.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(codciudad2);
        codciudad2.setBounds(160, 120, 40, 30);

        descriciudad2.setEditable(false);
        descriciudad2.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(descriciudad2);
        descriciudad2.setBounds(200, 120, 80, 30);

        jButton3.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jButton3.setText("Buscar Tipo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton3FocusGained(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(280, 120, 120, 30);

        jLabel8.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tamaño");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(430, 120, 50, 30);

        codciudad3.setEditable(false);
        codciudad3.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(codciudad3);
        codciudad3.setBounds(480, 120, 40, 30);

        descriciudad3.setEditable(false);
        descriciudad3.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(descriciudad3);
        descriciudad3.setBounds(520, 120, 80, 30);

        jButton4.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jButton4.setText("Buscar Color");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton4FocusGained(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(600, 120, 140, 30);

        jLabel9.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Modelo");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(760, 120, 50, 30);

        codciudad4.setEditable(false);
        codciudad4.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(codciudad4);
        codciudad4.setBounds(810, 120, 40, 30);

        descriciudad4.setEditable(false);
        descriciudad4.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(descriciudad4);
        descriciudad4.setBounds(850, 120, 100, 30);

        jButton5.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jButton5.setText("Buscar Modelo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton5FocusGained(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(950, 120, 120, 30);

        jLabel10.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Cliente");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(430, 180, 50, 30);

        codciudad5.setEditable(false);
        codciudad5.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(codciudad5);
        codciudad5.setBounds(480, 180, 40, 30);

        descriciudad5.setEditable(false);
        descriciudad5.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(descriciudad5);
        descriciudad5.setBounds(520, 180, 180, 30);

        jButton6.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jButton6.setText("Buscar Cliente");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButton6FocusGained(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(800, 180, 140, 30);

        descriciudad6.setEditable(false);
        descriciudad6.setFont(new java.awt.Font("Purisa", 0, 10)); // NOI18N
        jPanel2.add(descriciudad6);
        descriciudad6.setBounds(700, 180, 80, 30);

        jTabbedPane1.addTab("Registro", jPanel2);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 50, 1250, 520);

        Salir.setFont(new java.awt.Font("Purisa", 1, 10)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        getContentPane().add(Salir);
        Salir.setBounds(1090, 570, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarActionPerformed
        Id= this.CampoCodigo.getText();
        Descripcion= this.CampoDescripcion.getText();
        marca= this.descriciudad1.getText();
        idcliente= this.codciudad5.getText();
        Nombre= this.descriciudad5.getText();
        ci= this.descriciudad6.getText();
        dispose();
    }//GEN-LAST:event_SeleccionarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_SalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jButton2.setEnabled(true);
        new CCategoria(new VCategoriaVehiculo()).iniciar(); 
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton1FocusGained
       this.codciudad.setText(VCategoriaVehiculo.Cod);
       this.descriciudad.setText(VCategoriaVehiculo.Cargo);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1FocusGained

    private void TablaConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaConsultaMouseClicked
this.Guardar.setEnabled(false);
  this.Modificar.setEnabled(true);
      this.Eliminar.setEnabled(true);
      this.Cancelar.setEnabled(true);
      this.CampoDescripcion.setEnabled(true);
      this.codciudad.setEnabled(true);
       this.descriciudad.setEnabled(true);
      this.nuevo.setEnabled(false);
       this.jButton1.setEnabled(true);
       this.jButton2.setEnabled(true);
       this.jButton3.setEnabled(true);
       this.jButton4.setEnabled(true);
       this.jButton5.setEnabled(true);
       this.jButton6.setEnabled(true);
// TODO add your handling code here:
    }//GEN-LAST:event_TablaConsultaMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
           this.nuevo.setEnabled(false);
           this.Cancelar.setEnabled(true);
           this.Guardar.setEnabled(true);
           this.CampoDescripcion.setEnabled(true);
           this.jButton1.setEnabled(true);
           this.CampoDescripcion.requestFocus();
// TODO add your handling code here:
    }//GEN-LAST:event_nuevoActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
           this.Modificar.setEnabled(false);
          this.Eliminar.setEnabled(false);
           this.Cancelar.setEnabled(false);
           this.Guardar.setEnabled(false);
            this.nuevo.setEnabled(true);
             this.jButton1.setEnabled(false);
             this.jButton2.setEnabled(false);
             this.jButton3.setEnabled(false);
             this.jButton4.setEnabled(false);
             this.jButton5.setEnabled(false);
             this.jButton6.setEnabled(false);
            this.CampoDescripcion.setEnabled(false);
 


// TODO add your handling code here:
    }//GEN-LAST:event_CancelarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.jButton3.setEnabled(true);
new CMarcaVehiculo(new VMarcaVehiculo()).iniciar(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton2FocusGained
        this.codciudad1.setText(VMarcaVehiculo.Cod);
       this.descriciudad1.setText(VMarcaVehiculo.Cargo);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2FocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.jButton4.setEnabled(true);
		new CTipoVehiculo(new VTipoVehiculo()).iniciar(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton3FocusGained
         this.codciudad2.setText(VTipoVehiculo.Cod);
       this.descriciudad2.setText(VTipoVehiculo.Cargo);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3FocusGained

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       this.jButton5.setEnabled(true);
	   new CColorVehiculo(new VColorVehiculo()).iniciar(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton4FocusGained
       this.codciudad3.setText(VColorVehiculo.Cod);
       this.descriciudad3.setText(VColorVehiculo.Cargo);
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton4FocusGained

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      new CModeloVehiculo(new VModeloVehiculo()).iniciar(); 
	  this.jButton6.setEnabled(true);
      // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton5FocusGained
          this.codciudad4.setText(VModeloVehiculo.Cod);
       this.descriciudad4.setText(VModeloVehiculo.Cargo);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton5FocusGained

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new CClientes(new VClientes()).iniciar(); 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButton6FocusGained
       this.codciudad5.setText(VClientes.Id);
       this.descriciudad5.setText(VClientes.Cliente);
        this.descriciudad6.setText(VClientes.ci);
       // TODO add your handling code here:
    }//GEN-LAST:event_jButton6FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
 new CVehiculos(new VVehiculo()).iniciar();   }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField CampoBuscar;
    public javax.swing.JTextField CampoCodigo;
    public javax.swing.JTextField CampoDescripcion;
    public javax.swing.JButton Cancelar;
    public javax.swing.JButton Eliminar;
    public javax.swing.JButton Guardar;
    public javax.swing.JButton Informe;
    public javax.swing.JButton Modificar;
    public javax.swing.JButton Salir;
    private javax.swing.JButton Seleccionar;
    public javax.swing.JTable TablaConsulta;
    public javax.swing.JTextField codciudad;
    public javax.swing.JTextField codciudad1;
    public javax.swing.JTextField codciudad2;
    public javax.swing.JTextField codciudad3;
    public javax.swing.JTextField codciudad4;
    public javax.swing.JTextField codciudad5;
    public javax.swing.JTextField descriciudad;
    public javax.swing.JTextField descriciudad1;
    public javax.swing.JTextField descriciudad2;
    public javax.swing.JTextField descriciudad3;
    public javax.swing.JTextField descriciudad4;
    public javax.swing.JTextField descriciudad5;
    public javax.swing.JTextField descriciudad6;
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JButton nuevo;
    // End of variables declaration//GEN-END:variables
}
